Force Merge Runner Improvements -  Polling
elastic/rally pull request #1051
Opened 2020-08-21 16:04 UTC by gingerwizard

This adds a polling mode to the force-merge runner and in the process closes https://github.com/elastic/rally/issues/1050

Some considerations:

1. The change adds a `mode` parameter. This defaults to `blocking` which causes the current behaviour. 
2. If set to `polling` we ignore the `request-timeout` parameter and timeout the force_merge API call after 1s. We then poll the tasks API at an interval of `poll-period` (default 10s), until no force-merge tasks are listed.
3. Currently there is no timeout on the tasks API calls. It is possible this is susceptible to cluster pressure and may itself timeout under heavy load. However, i believe this represents a valid error condition.
4. The 1s timeout is a workaround to the force_merge API not supporting an async call and returning a task id. If multiple force_merge calls are issued in different runners in parallel, all force merges must complete to unblock. This seems low risk as consecutive calls are effectively a noop if `max-num-segments` has been reached.

Will add docs once parameter naming and usage is agreed.

2020-08-24 09:36 UTC, gingerwizard commented
@dliappis This is ready for an initial review now all CI tests pass.

2020-08-25 16:43 UTC, dliappis requested changes
Thank you for this super useful addition!

I left a number of style comments (unfortunately we skip many errors that pylint would normally report, see #838)

I haven't tested this yet, will do this asap.

2020-08-31 16:02 UTC, gingerwizard commented
@dliappis i believe i have addressed the formatting issues. If you're happy with the approach i'll add docs.

2020-09-09 08:49 UTC, dliappis commented on docs/recipes.rst
> +
FYI These doc fragmants seem to have come from https://github.com/elastic/rally/pull/1051/commits/89ed934ad78088260620f742b9e2e170b5a9b9b6 (they've already been merged in https://github.com/elastic/rally/pull/1049).

2020-09-10 06:32 UTC, dliappis reviewed
@gingerwizard I tested this yesterday in a real long benchmark where force merging down to 1 segment takes a very long time the polling mode worked marvelously. Let's proceed with docs.

2020-09-14 07:02 UTC, dliappis reviewed
Have you added docs already for the polling mode of the force merge runner? I didn't see anything in this review cycle.

2020-09-14 07:02 UTC, dliappis commented on docs/recipes.rst
> +
@gingerwizard I still see this unrelated recipe in docs (coming from the older PR).

2020-09-14 07:03 UTC, dliappis commented
@elasticmachine test this

2020-09-14 07:04 UTC, dliappis commented
@elasticmachine run tests

2020-09-14 09:36 UTC, closed without merging