Make S3 support optional
elastic/rally pull request #1252
Opened 2021-04-25 21:14 UTC by pquentin

Closes #1095.

With this pull request, boto3 is no longer installed by default but should be installed using `python -m pip install esrally[s3]` instead.

When a S3 `base-url` is provided, here's what users see:

```
[INFO] Preparing for race ...
[ERROR] S3 support is optional. Install it with `python -m pip install esrally[s3]`

[ERROR] Cannot race. Error in track preparator
        No module named 'boto3'

...
```

So, we let the `ImportError` propagate, but also explain how to get S3 support.

To test this manually in an existing virtual environment, uninstalling boto3 manually is not enough, as `pkg_resource.require("esrally")` will complain that it's missing. Recreating the virtual environment from scratch and removing any .egg-info files should fix this.

For what it's worth, I haven't managed to get the integration tests to work locally, but they don't seem to use S3, so they probably still pass.

2021-04-25 21:20 UTC, pquentin commented on esrally/utils/net.py
> +    # order to simulate the absence of boto3
This is quite ugly, but the alternative is to use `del sys.modules["boto3"]`, which is an ugly and global hack, and likely to break things. While we use this hack succesfully in urllib3 to test support for Python versions without ssl, this:

 * has caused [huge headaches in a project that adds async support to urllib3](https://github.com/python-trio/hip/pull/42#issuecomment-386304273) and
 * would prevent running tests in parallel.

So I would suggest avoiding touching `sys.modules`.

2021-04-27 13:20 UTC, DJRickyB commented
@elasticmachine run tests please

2021-04-27 13:29 UTC, pquentin commented
Thanks for running the tests! I'll fix the lint

2021-04-27 13:41 UTC, pquentin commented
@DJRickyB Can you please run the tests again? I guess @elasticmachine won't listen if I try to ask myself

2021-04-27 13:42 UTC, DJRickyB commented
@elasticmachine run tests

2021-04-27 14:51 UTC, DJRickyB requested changes
@pquentin thanks a ton! I have one remaining requirement before approval: please preserve the behavior where `make install` ends up installing boto3+dependencies. for our purposes I think it's ok if `[s3]` resolution occurs in either `make install-user` or a new `make` target altogether

2021-04-27 15:06 UTC, pquentin commented
@DJRickyB Thank you for the review! Done

2021-04-27 16:00 UTC, DJRickyB approved these changes
Looks good to me.  Thank you once again for your contribution

2021-04-27 16:00 UTC, merged

2021-04-27 16:20 UTC, pquentin commented
Thank _you_ for the quick reviews! I'll work on making GCS support optional next.

2021-04-27 17:44 UTC, DJRickyB commented
@pquentin thank you, but we are looking at keeping GCS support first-class for the time being