Add create and delete ILM policy runners
elastic/rally pull request #1303
Opened 2021-07-15 05:10 UTC by b-deam

With this commit we add both `create-ilm-policy` and
`delete-ilm-policy` operations via their respective runners.

Closes https://github.com/elastic/rally/issues/1087

Tested with track:
<details>

<summary> Track JSON </summary>

```
{
  "version": 1,
  "description": "Testing ILM Runners"
  "challenges": [
    {
      "name": "ilm-policy",
      "schedule": [
        {
          "operation": {
            "operation-type": "create-ilm-policy",
            "policy-name": "my-ilm-policy",
            "body": {
              "policy": {
                "phases": {
                  "hot": {
                    "min_age": "0ms",
                    "actions": {
                      "rollover": {
                        "max_age": "30d"
                      },
                      "set_priority": {
                        "priority": 100
                      }
                    }
                  }
                }
              }
            }
          }
        },
        {
          "operation": {
            "operation-type": "delete-ilm-policy",
            "policy-name": "my-ilm-policy"
          }
        }
      ]
    }
  ]
}
```

</details>

2021-07-22 06:18 UTC, b-deam commented
Heya @DJRickyB, can you please review when you get a second :-)

2021-07-22 11:36 UTC, DJRickyB requested changes
Sorry for the delay. Looks great minus one little thing in the tests

2021-07-22 11:36 UTC, DJRickyB commented on tests/driver/runner_test.py
> +        del self.params["request-params"]
if we wanted to add any more tests to this class, this would be side-effecty i think. probably best to copy the params first before mangling

2021-07-22 11:36 UTC, DJRickyB commented on tests/driver/runner_test.py
> +        del self.params["request-params"]
same as above

2021-07-25 23:10 UTC, b-deam commented
Thanks for the review @DJRickyB - I've made the requested changes :-)

2021-07-26 14:37 UTC, DJRickyB approved these changes
Officially LGTM

2021-07-26 22:03 UTC, merged