Update adding tracks documentation
elastic/rally pull request #1383
Opened 2021-11-12 12:51 UTC by uparamonau-es

Updating Rally documentation to fix inconsistencies discovered during onboarding.

2021-11-12 12:54 UTC, uparamonau-es commented
All the listed JSONs/code/command lines have been verified with ES 6.5.3 and 7.14.1 up to Advanced Topics section which seems not so type/mapping-specific as the first part.

2021-11-16 05:42 UTC, pquentin requested changes
Thanks! I like this a lot because:

 1. 7.x (and soon 8.x) become the normal cases instead of the exceptional one
 2. When we drop support for 6.x, this page will be easy to update (just remove a bunch of stuff)

I left a few suggestions about typography mostly, you should be able to commit them directly from the GitHub interface.

2021-11-16 05:42 UTC, pquentin commented on docs/adding_tracks.rst
> +   This tutorial assumes that you want to benchmark a version of Elasticsearch 7.0.0 or later. If you want to benchmark Elasticsearch prior to 7.0.0 you need to add the mapping type above so ''index.
```suggestion
   This tutorial assumes that you want to benchmark a version of Elasticsearch 7.0.0 or later. If you want to benchmark Elasticsearch prior to 7.0.0 you need to add the mapping type above so ``index.json`` will look like::
```

2021-11-16 05:42 UTC, pquentin commented on docs/adding_tracks.rst
> +   This tutorial assumes that you want to benchmark a version of Elasticsearch 7.0.0 or later. If you want to benchmark Elasticsearch prior to 7.0.0 you need to add the ``types`` property above so ''
```suggestion
   This tutorial assumes that you want to benchmark a version of Elasticsearch 7.0.0 or later. If you want to benchmark Elasticsearch prior to 7.0.0 you need to add the ``types`` property above so ``track.json`` will look like::
```

2021-11-16 05:42 UTC, pquentin commented on docs/adding_tracks.rst
> +    To test the track with Elasticsearch prior 7.0.0 you need to update ''index.json'' and ''track.json'' as specified in notes above and then execute ``esrally race --distribution-version=6.5.3 --tr
```suggestion
    To test the track with Elasticsearch prior to 7.0.0 you need to update ``index.json`` and ``track.json`` as specified in notes above and then execute ``esrally race --distribution-version=6.5.3 --track-path=~/rally-tracks/tutorial``.
```

2021-11-16 05:42 UTC, pquentin commented on docs/adding_tracks.rst
> +    To use the track with Elasticsearch prior 7.0.0 you need to update ''index.json'' and ''track.json'' with index and mapping types accordingly as specified in notes above.
```suggestion
    To use the track with Elasticsearch prior to 7.0.0 you need to update ``index.json`` and ``track.json`` with index and mapping types accordingly as specified in notes above.
```

2021-11-16 05:42 UTC, pquentin commented on docs/adding_tracks.rst
> +    Please remember about index and mapping types usage in ''index.json'' and ''track.json'' in Elasticsearch prior 7.0.0 as specified in notes above.
```suggestion
    Please remember about index and mapping types usage in ``index.json`` and ``track.json`` in Elasticsearch prior to 7.0.0 as specified in notes above.
```

2021-11-16 07:53 UTC, pquentin approved these changes

2021-11-16 13:55 UTC, merged