Set included files and directories for black
elastic/rally pull request #1508
Opened 2022-06-01 18:04 UTC by j-bennet

This is so `black .` doesn't make unintended changes.

2022-06-02 09:47 UTC, pquentin requested changes
Thanks for fixing this! However, we are now storing the list of included folders in two places. What are your thoughts on just running black/isort on everything, including changelog.py and docs/conf.py?

This would fix `black .`, remove some extra config, and allow me to edit changelog.py and docs/conf.py with my editor without ruining the formatting.

2022-06-02 16:24 UTC, j-bennet commented
After running `black` on everything, 3 files ended up with changes:

```
	modified:   changelog.py
	modified:   docs/conf.py
	modified:   docs/create_scheduler_plot.py
```

If there's no specific reason to include `docs`, I'd rather `black` everything.

2022-06-02 18:19 UTC, pquentin reviewed
Thank you! Yes, your new proposal is the right thing to do: there is no good reason why those were left out, they were not linted so I did not format them.

I left a few trailing commas as suggestions, this will tell black to restore those lines as blocks.

2022-06-02 18:19 UTC, pquentin commented on docs/conf.py
> +extensions = ["sphinx.ext.ifconfig"]
```suggestion
extensions = ["sphinx.ext.ifconfig",]
```

2022-06-02 18:19 UTC, pquentin commented on docs/conf.py
> +GLOBAL_SUBSTITUTIONS = {"{MIN_PY_VER}": read_min_python_version()}
```suggestion
GLOBAL_SUBSTITUTIONS = {"{MIN_PY_VER}": read_min_python_version(),}
```

2022-06-02 18:19 UTC, pquentin commented on docs/conf.py
> +    (master_doc, "Rally.tex", "Rally Documentation", "Daniel Mitterdorfer", "manual"),
```suggestion
    (master_doc, "Rally.tex", "Rally Documentation", "Daniel Mitterdorfer", "manual",),
```

2022-06-02 18:19 UTC, pquentin commented on docs/conf.py
> +man_pages = [(master_doc, "esrally", "Rally Documentation", [author], 1)]
```suggestion
man_pages = [(master_doc, "esrally", "Rally Documentation", [author], 1,)]
```

2022-06-02 18:19 UTC, pquentin commented on docs/conf.py
> +    (master_doc, "Rally", "Rally Documentation", author, "Rally", "Macrobenchmarking framework for Elasticsearch.", "Miscellaneous"),
```suggestion
    (master_doc, "Rally", "Rally Documentation", author, "Rally", "Macrobenchmarking framework for Elasticsearch.", "Miscellaneous",),
```

2022-06-04 19:02 UTC, pquentin approved these changes
Thanks for bearing with me! LGTM.

2022-06-06 18:31 UTC, merged