Add additional filter options to list races
elastic/rally pull request #1597
Opened 2022-10-13 17:12 UTC by ebadyano

2022-10-27 14:52 UTC, michaelbaamonde requested changes
I tested out the basic functionality with both a local and remote metrics store and it worked well! This is a very nice improvement, thanks.

In addition to my comments on adjusting the help text, I think we should add a unit test for the new filtering logic contained in `metrics.py`.

2022-10-27 14:52 UTC, michaelbaamonde commented on esrally/rally.py
> +    list_parser.add_argument(
With the way things are structured right now, all `list` commands will accept these new race-specific arguments, but can't do anything useful with them. It's not a huge deal, but seeing them in the `--help` output for something like `esrally list tracks --help` could add some confusion.

That said, there's already precedent for this. `--limit` only really applies to races, but you can pass it to any other `list` subcommand.

Could you perhaps change the help text for the new arguments to indicate that they're intended to be used for races only? Something like `Show only races for this track` in this case, for example.

2022-10-28 16:56 UTC, ebadyano commented
@michaelbaamonde thank you for your review. I added unit tests for the new filter logic. Thank you!

2022-11-02 15:28 UTC, michaelbaamonde approved these changes
LGTM!

2022-11-02 15:48 UTC, merged