closes#1694 Configurable timezone for Rally logging
elastic/rally pull request #1699
Opened 2023-03-31 11:36 UTC by vaibhavsolanki1193

* Have you signed the [contributor license agreement](https://www.elastic.co/contributor-agreement)? YES
* Have you followed the [contributor guidelines](https://github.com/elastic/rally/blob/master/CONTRIBUTING.md)? YES
* Have you run `make check-all` successfully? YES
* Did you choose a [descriptive title and description](https://chris.beams.io/posts/git-commit/) for your PR? YES
* (Only for maintainers) Did you apply appropriate labels and a milestone? _SKIP_

2023-03-31 11:41 UTC, vaibhavsolanki1193 commented
I have signed the [Contributor Agreement](https://www.elastic.co/contributor-agreement). Please trigger the bot check again.

2023-03-31 11:47 UTC, pquentin commented
@elasticmachine test this please

2023-03-31 12:14 UTC, pquentin commented
buildkite build this please

2023-04-05 11:34 UTC, vaibhavsolanki1193 commented
@pquentin  please review once again. 
```
esrally race --track=http_logs --test-mode
```
is working now. Thank you

2023-04-05 11:47 UTC, pquentin commented
buildkite build this please

2023-04-05 14:06 UTC, pquentin commented
Thanks, I see all existing tests are passing now. I'll try to review this tomorrow.

2023-04-13 07:52 UTC, pquentin requested changes
Sorry for the delay. I finally took some time to dig into this. If we look at the proposed solutions, we have four of them:

1. This pull request: `datetime.utcnow().astimezone().tzinfo`
2. This pull request: `pytz.timezone()`
3. The GitHub issue: using `time.user_tz`
4. The Discuss topic: allow switching from `time.gmtime()` to `time.localtime()`

The problem is that most of them just don't work.

1. Is not reliable if you start Rally *during* a DST change (see PEP 495 for details). More importantly, it's also not reliable if Rally continues running after a timezone change: it will keep using the previous offset.
2. does not work in various timezones, see https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html for details (including why fixing it to use `localize()` would be slower)
3. is unreliable as `user_tz` ignores DST, so it would be off half of the year. There are ways to fix it (see https://docs.python.org/3/library/time.html#timezone-constants and the Note) but it would still suffer from the fact we won't update the UTC offset after a DST change.

While there are ways to fix 2. I think I showed that timezone are complicated enough that we should try to avoid them because there are probably other issues I'm not aware of. The fourth solution is the simplest and also the only that actually works.

Can you please implement the following changes?

* update your implementation so that setting `timezone` to `localtime` uses `time.localtime()` instead of `time.gmtime()` and remove all timezone considerations
* document this feature in https://esrally.readthedocs.io/en/stable/configuration.html#logging
* rename `configure_utc_formatter` to `configure_time_formatter`
* add tests for `configure_time_formatter` under `tests/log_test.py`

Then we'll be ready to merge!

Sorry that we're only noticing this now. Your work has been very valuable: having a working implementation made it easier to reason about possible issues.

2023-04-14 15:46 UTC, vaibhavsolanki1193 commented
Thank you @pquentin for the detailed inputs. I have modified the code as advised. Please review it once you get a chance!

2023-04-14 16:00 UTC, pquentin commented
buildkite build this please

2023-04-15 11:47 UTC, pquentin commented
Do you need help for adding the unit test?

2023-04-15 15:32 UTC, vaibhavsolanki1193 commented
The test cases were done however I was working around an issue I observed so please check the details below:

**Issue**: After this change gets merged, the local configuration file @ `~/.rally/logging.json` was still pointing to `esrally.log.configure_utc_formatter` which caused esrally fail to run. 
Running `./rally --help` gave this error:
```
Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/logging/config.py", line 392, in resolve
    self.importer(used)
ModuleNotFoundError: No module named 'esrally.log.configure_utc_formatter'; 'esrally.log' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/codespace/.python/current/lib/python3.10/logging/config.py", line 544, in configure
    formatters[name] = self.configure_formatter(
  File "/home/codespace/.python/current/lib/python3.10/logging/config.py", line 656, in configure_formatter
    result = self.configure_custom(config)
  File "/home/codespace/.python/current/lib/python3.10/logging/config.py", line 471, in configure_custom
    c = self.resolve(c)
  File "/home/codespace/.python/current/lib/python3.10/logging/config.py", line 399, in resolve
    raise v
  File "/home/codespace/.python/current/lib/python3.10/logging/config.py", line 392, in resolve
    self.importer(used)
ValueError: Cannot resolve 'esrally.log.configure_utc_formatter': No module named 'esrally.log.configure_utc_formatter'; 'esrally.log' is not a package
```
**Steps tried to fix**:
```python
make prereq
make install
source .venv/bin/activate
./rally --help
```
I was expecting `make install` might also update the local logging.json, but that didn't happen. 

**Resolution**: Manually replaced `esrally.log.configure_utc_formatter` to `esrally.log.configure_time_formatter`

Please advise if you think this could be a breaking change or if handling the local logging.json is out of scope for esrally.

If this is considered an issue, a quick fix could be to replace the function name `configure_time_formatter` back to `configure_utc_formatter`. I would love to hear your thoughts on this. Thank you!

2023-06-02 13:14 UTC, pquentin requested changes
I'm sorry for the bad experience you're having here with the big delay between reviews. We're nearly there.

The main issue was the migration to the new formatter. To address this, I pushed https://github.com/elastic/rally/pull/1699/commits/2f547366ba17b6f4b87d25a22a8ec414314eb8b4 and https://github.com/elastic/rally/pull/1699/commits/f1dce9f4997bf7baf52d5dd5bc8a69ed99e58d2b. Please tell me what you think.

2023-06-05 11:53 UTC, vaibhavsolanki1193 commented on esrally/resources/logging.json
> +      "()": "esrally.log.configure_time_formatter"
I also suggested the same but wanted to discuss the possibilities of other solutions. Thank you for your input and time.

2023-06-05 11:54 UTC, vaibhavsolanki1193 commented
no problem at all @pquentin. I also agree with the new changes.

2023-06-05 11:59 UTC, pquentin commented
buildkite build this please

2023-06-08 14:58 UTC, closed without merging