Bulk http status & 429 retries
elastic/rally pull request #1868
Opened 2024-08-02 17:40 UTC by gareth-ellis

2024-12-19 09:35 UTC, gbanasiak commented
Context: https://elastic.slack.com/archives/C03P67VQAP2/p1721939793707489

2025-11-18 20:18 UTC, gareth-ellis commented
@elasticmachine update branch

2026-01-16 10:35 UTC, gareth-ellis commented
My approach so far seems to work - Please take a look

2026-01-16 12:29 UTC, gareth-ellis commented
@elasticmachine update branch

2026-01-19 08:24 UTC, gareth-ellis commented
The failures are due to me changing the parameters for detailed_stats - https://github.com/elastic/rally-tracks/blob/master/elastic/shared/runners/bulk.py#L36C25-L36C39

I guess I can either
a) implement the retry in a new operation - RetryingBulk?
b) avoid changing parameters and pass via params - though i would then need to avoid returning lines_to_retry - 
c) Update elastic/logs, but that would still risk breaking other tracks that external users have written (if they follow the same approach as elastic/logs

thoughts?

2026-01-20 14:41 UTC, gbanasiak reviewed
This is an interesting coupling problem with `super().detailed_stats(...)` used in elastic/logs. Tracks version control is only for ES, not for Rally, so changing custom `detailed_stats()` say like below will fail when calling parent's method in old Rally.

```
    def detailed_stats(self, params, response, emit_lines_to_retry=False):
        stats = super().detailed_stats(params, response, emit_lines_to_retry) <--- HERE
        return {**stats, **params["param-source-stats"]}
```

It would be best if we minimized the surface between tracks code and rally code. Our [docs](https://esrally.readthedocs.io/en/stable/advanced.html#creating-your-own-operations-with-custom-runners) only mention top-level runner call with `es` and `params` arguments. Due to this I would be happy to declare that what this particular runner is doing as not supported. I would even go as far as clarify this in documentation.

My vote would be to change elastic/logs custom runner to avoid calling `detailed_stats()` completely and backport this to _all_ branches where modified Rally might potentially be used, so I'd say all 8.x up until now.

Something like this perhaps?

```
class RawBulkIndex(BulkIndex):
    async def __call__(self, es, params):
        meta_data = await super().__call__(es, params)
        if params.get("detailed-results", False):
            meta_data.update(params["param-source-stats"])
        return meta_data
```

The alternative would be to _keep_ `detailed_results()` as is, and determine documents to retry separately but that means iterating through a response twice which would impact processing time.

I'm curious about @fressi-elastic thoughts on that one as well.

I'm adding further comments below.

---

I think we also planned on adding exponential back-off. Is this still a plan, or not in this PR?

2026-01-20 14:41 UTC, gbanasiak commented on esrally/driver/runner.py
> +                sum_total_document_size_bytes += stats["total-document-size-bytes"]
Isn't there a risk of `KeyError` in case of simple stats here? There are no `bulk-request-size-bytes` and `total-document-size-bytes` keys in stats dictionary returned by `simple_stats()` ?

2026-01-20 14:41 UTC, gbanasiak commented on esrally/driver/runner.py
> +            bulk_size = len(lines_to_retry) / 2  # at this point the data always contains action metadata.
> at this point the data always contains action metadata

This is a slight off-topic:

I've spent some time digging once I saw this comment. I think bulk runner always receives action-and-metadata lines in the `body` param today (see [here](https://github.com/elastic/rally/blob/a9c3ab99ee4029c592ee7b85912fa1fa19fad225/esrally/track/params.py#L1062)). If corpus does not include them they are generated in earlier processing stages. I don't quite understand this from the above code:

```
        if with_action_metadata:
            api_kwargs.pop("index", None)
            # only half of the lines are documents
            response = await es.bulk(params=bulk_params, **api_kwargs)
        else:
            response = await es.bulk(doc_type=params.get("type"), params=bulk_params, **api_kwargs)
```

The `only half of the lines are documents` comment suggests the `else` clause is different, but it isn't. There's nothing in `bulk()` method of ES client that would magically add action-and-metadata lines. Also `doc_type` is ignored I think, it's a leftover from old ES versions.

I think we could simplify / remove this.

2026-01-20 14:41 UTC, gbanasiak commented on esrally/driver/runner.py
> +                }
This exposes the details of stats at `_call__()` level which were previously hidden either in `simple_stats()` or `detailed_stats()`. Can we avoid this? We could have a method that iterates through response documents, and:
* calls another method (passed as an argument) that increases stats counters for each document,
* builds a retry list (optionally).

2026-01-21 12:53 UTC, gareth-ellis commented on esrally/driver/runner.py
> +                sum_total_document_size_bytes += stats["total-document-size-bytes"]
Ah yes - you can see which variant i've been testing with ;) fixed in 04879dbb744934119bde082d1486230778c38b89

2026-01-21 13:02 UTC, gareth-ellis commented on esrally/driver/runner.py
> +            bulk_size = len(lines_to_retry) / 2  # at this point the data always contains action metadata.
Yea - it seems at one point we calculated the number of documents here, but that was removed and the comment not removed. I'll remove the comment for now, I think i would need to test a little more whether we have code paths that use the with_action_metadata or not

2026-01-27 15:05 UTC, fressi-elastic requested changes
I spot some opportunities to simplify your code and remove code duplication.

I also don't think changing the return type of `simple_stats` and `detailed_stats` is save and necessary having tracks extending this class and potentially already calling this methods. It would be simpler adding a third method to extract retry_lines and fill additional data to stats dictionary.

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +            bulk_size = len(lines_to_retry) / 2  # at this point the data always contains action metadata.
Can you explain why bulk size is the half of lines to retry?

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +        total_success = total_error = total_time = sum_bulk_request_size_bytes = sum_total_document_size_bytes = 0
Please think about regrouping variables (and part of the behavior) in some data class. There are too many variables here and it is getting hard to keep track of all the variables this function has. In alternative please also think about splitting the method in sub-methods.

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +        stats, lines_to_retry = (
I generally prefer the simplicity of a normal if block. I see no advantage on putting the if in the middle instead of the beginning of the block.

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +        stats, lines_to_retry = (
Could we have `lines_to_retry` as a new attribute of stats? Which type `stats` is? Without type hints this is very hard to follow for me.

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +            if len(lines_to_retry) == 0:
if not lines_to_retry

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +                max_doc_status = max(max_doc_status, data["status"])
Why are you keeping the maximum value of status codes? Which is the purpose?

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +    def get_bulk_lines(self, params):
The `return` statements here make all `elfi` replaceable with `if` and the final `else` rendundant.

2026-01-27 15:05 UTC, fressi-elastic commented on esrally/driver/runner.py
> +    def simple_stats(self, bulk_size, unit, response, params, emit_lines_to_retry=False):
You are adding the same logic to both sible_stats and detailed_stats. You could make instead a 3rd function that add missing data after calling one of the two. Current code would be much simpler and easy to understand:

```Python
if detailed_results:
  stats = self.detailed_stats(...)
else:
  stats = self.simple_stats(...)
if retries_on_429 > 0:
  lines_to_retry = self.lines_to_retry(stats)
```

2026-01-27 15:08 UTC, gareth-ellis commented on esrally/driver/runner.py
> +            bulk_size = len(lines_to_retry) / 2  # at this point the data always contains action metadata.
Because that's how bulk requests works - there is an action line, and a data line, when we talk about 2500 documents, the request will contain 5000 lines

2026-01-27 15:10 UTC, fressi-elastic commented
Please pay attention there are tracks that are using a runner that extends this one:

https://github.com/elastic/rally-tracks/blob/master/elastic/shared/runners/bulk.py#L21

Please make sure we are testing this PR with such tracks too (if CI is not already doing it).

2026-02-18 14:12 UTC, gareth-ellis commented on esrally/driver/runner.py
> +    def simple_stats(self, bulk_size, unit, response, params, emit_lines_to_retry=False):
I've change this slightly 1895973

2026-02-19 10:38 UTC, gbanasiak reviewed
This looks good to me. I've added some non-blocking comments after going through the code. Can we have a unit test showing at least a single retry in action together with stats accumulation?

It would be great to add exponential back-off, but this can be done in a follow-up.

2026-02-19 10:38 UTC, gbanasiak commented on esrally/driver/runner.py
> +    error_count: int
Why `success_count` is optional? Can we default both `success_count` and `error_count` to 0?

2026-02-19 10:38 UTC, gbanasiak commented on esrally/driver/runner.py
> +        self.max_doc_status = other.max_doc_status
The fact that some things get increased while others replaced when accumulating might not be obvious to the first-time reader. I think I would add a comment on top of `accumulate()` to explain that.

2026-02-19 10:38 UTC, gbanasiak commented on esrally/driver/runner.py
> +            bulk_size = len(lines_to_retry) / 2
I would replace `len(lines_to_retry) / 2` with `len(stats.error_429_indices)`. You can calculate this length only once.

2026-02-19 10:38 UTC, gbanasiak commented on esrally/driver/runner.py
> +        bulk_lines = self.get_bulk_lines(api_kwargs)
`bulk_lines` remains the same throughout entire lifetime of the runner's call. Can we avoid recalculating it on every retry?

2026-02-19 10:38 UTC, gbanasiak commented on esrally/driver/runner.py
> +                self.logger.warning("%s after bulk request retry. Payload: %s", response.meta.status, lines_to_retry)
There is a potential for very long output here. I would only inform about selected stats at `warning` level.

2026-02-19 10:38 UTC, gbanasiak commented on esrally/driver/runner.py
> +                max_doc_status = max(max_doc_status, data["status"])
It gives us an indication of what was the worst treatment any of the potentially thousands of documents received as part of processing a bulk request. Status codes are sorted by severity in a sense.

2026-02-19 10:49 UTC, gareth-ellis commented on esrally/driver/runner.py
> +                self.logger.warning("%s after bulk request retry. Payload: %s", response.meta.status, lines_to_retry)
yes. I can switch that to debug - i was using it for diagnosing another issue,

2026-02-19 12:09 UTC, gbanasiak commented on tests/driver/runner_test.py
> +        assert result["retry-count"] == 3
Shouldn't `retry-count` be equal 2? 1 regular call + 2 retries...

2026-02-19 13:47 UTC, gareth-ellis commented on tests/driver/runner_test.py
> +        assert result["retry-count"] == 3
Fixed - i had initially set this as a count of requests, so after the first retry we set to 2 rather than 1. Fixed that now

2026-02-19 15:35 UTC, gbanasiak approved these changes
LGTM

2026-02-23 11:24 UTC, fressi-elastic approved these changes

2026-02-23 13:01 UTC, merged